# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5233:5233
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
